=== aaronparker/vcredist/VisualCRedistributables.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Redistributables">
    <xs:annotation>
      <xs:documentation>https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Platform" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Redistributable" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element type="xs:string" name="Name"/>
                    <xs:element type="xs:string" name="ShortName"/>
                    <xs:element type="xs:string" name="URL"/>
                    <xs:element type="xs:string" name="ProductCode"/>
                    <xs:element type="xs:string" name="Download"/>
                  </xs:choice>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="Architecture" use="optional"/>
            <xs:attribute type="xs:short" name="Release" use="optional"/>
            <xs:attribute type="xs:string" name="Install" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== aaronparker/vcredist/VisualCRedistributables.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads -->
<Redistributables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='https://raw.githubusercontent.com/aaronparker/appinstall-scripts/master/Install-VisualCRedistributables/VisualCRedistributables.xsd'>
    <Platform Architecture="x64" Release="2005" Install="/Q">
        <Redistributable>
            <Name>Microsoft Visual C++ 2005 Service Pack 1 Redistributable Package MFC Security Update</Name>
            <ShortName>MFC</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=26347</URL>
            <Download>https://download.microsoft.com/download/8/B/4/8B42259F-5D70-43F4-AC2E-4B208FD8D66A/vcredist_x64.EXE</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2005 Service Pack 1 Redistributable Package ATL Security Update</Name>
            <ShortName>ATL</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=14431</URL>
            <Download>https://download.microsoft.com/download/6/B/B/6BB661D6-A8AE-4819-B79F-236472F6070C/vcredist_x64.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2005 SP1 Redistributable Package (x64)</Name>
            <ShortName>SP1</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=18471</URL>
            <Download>https://download.microsoft.com/download/d/4/1/d41aca8a-faa5-49a7-a5f2-ea0aa4587da0/vcredist_x64.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2005 Redistributable Package (x64)</Name>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=21254</URL>
            <ShortName>RTM</ShortName>
            <Download>https://download.microsoft.com/download/9/1/4/914851c6-9141-443b-bdb4-8bad3a57bea9/vcredist_x64.exe</Download>
        </Redistributable>
    </Platform>
    <Platform Architecture="x86" Release="2005" Install="/Q">
        <Redistributable>
            <Name>Microsoft Visual C++ 2005 Service Pack 1 Redistributable Package MFC Security Update</Name>
            <ShortName>MFC</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=26347</URL>
            <Download>https://download.microsoft.com/download/8/B/4/8B42259F-5D70-43F4-AC2E-4B208FD8D66A/vcredist_x86.EXE</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2005 Service Pack 1 Redistributable Package ATL Security Update</Name>
            <ShortName>ATL</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=14431</URL>
            <Download>https://download.microsoft.com/download/6/B/B/6BB661D6-A8AE-4819-B79F-236472F6070C/vcredist_x86.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2005 SP1 Redistributable Package (x86)</Name>
            <ShortName>SP1</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=5638</URL>
            <Download>https://download.microsoft.com/download/e/1/c/e1c773de-73ba-494a-a5ba-f24906ecf088/vcredist_x86.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2005 Redistributable Package (x86)</Name>
            <ShortName>RTM</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=3387</URL>
            <Download>https://download.microsoft.com/download/d/3/4/d342efa6-3266-4157-a2ec-5174867be706/vcredist_x86.exe</Download>
        </Redistributable>
    </Platform>
    <Platform Architecture="x64" Release="2008" Install="/Q">
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 Redistributable Package (x64)</Name>
            <ShortName>RTM</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=15336</URL>
            <Download>https://download.microsoft.com/download/d/2/4/d242c3fb-da5a-4542-ad66-f9661d0a8d19/vcredist_x64.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 Feature Pack Redistributable Package (x64)</Name>
            <ShortName>FP</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=16771</URL>
            <Download>https://download.microsoft.com/download/1/9/0/190da410-d595-4342-ba2f-2422e78bc84d/vcredist_x64.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 Redistributable Package ATL Security Update</Name>
            <ShortName>ATL</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=10430</URL>
            <Download>https://download.microsoft.com/download/A/5/3/A53B40CA-F75C-4678-852A-3C15EA82F186/vcredist_x64.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 SP1 Redistributable Package (x64)</Name>
            <ShortName>SP1</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=2092</URL>
            <Download>https://download.microsoft.com/download/2/d/6/2d61c766-107b-409d-8fba-c39e61ca08e8/vcredist_x64.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 Service Pack 1 Redistributable Package ATL Security Update</Name>
            <ShortName>SP1ATL</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=11895</URL>
            <Download>https://download.microsoft.com/download/9/7/7/977B481A-7BA6-4E30-AC40-ED51EB2028F2/vcredist_x64.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 Service Pack 1 Redistributable Package MFC Security Update</Name>
            <ShortName>SP1MFC</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=26368</URL>
            <Download>https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x64.exe</Download>
        </Redistributable>
    </Platform>
    <Platform Architecture="x86" Release="2008" Install="/Q">
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 Redistributable Package (x86)</Name>
            <ShortName>RTM</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=29</URL>
            <Download>https://download.microsoft.com/download/1/1/1/1116b75a-9ec3-481a-a3c8-1777b5381140/vcredist_x86.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 Feature Pack Redistributable Package (x86)</Name>
            <ShortName>FP</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=10015</URL>
            <Download>https://download.microsoft.com/download/d/1/0/d10d210e-e0ad-4010-b547-bc5e395ef691/vcredist_x86.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 Redistributable Package ATL Security Update</Name>
            <ShortName>ATL</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=10430</URL>
            <Download>https://download.microsoft.com/download/A/5/3/A53B40CA-F75C-4678-852A-3C15EA82F186/vcredist_x86.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 SP1 Redistributable Package (x86)</Name>
            <ShortName>SP1</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=5582</URL>
            <Download>https://download.microsoft.com/download/d/d/9/dd9a82d0-52ef-40db-8dab-795376989c03/vcredist_x86.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 Service Pack 1 Redistributable Package ATL Security Update</Name>
            <ShortName>SP1ATL</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=11895</URL>
            <Download>https://download.microsoft.com/download/9/7/7/977B481A-7BA6-4E30-AC40-ED51EB2028F2/vcredist_x86.exe</Download>
        </Redistributable>
        <Redistributable>
            <Name>Microsoft Visual C++ 2008 Service Pack 1 Redistributable Package MFC Security Update</Name>
            <ShortName>SP1MFC</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=26368</URL>
            <Download>https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe</Download>
        </Redistributable>
    </Platform>
    <Platform Architecture="x64" Release="2010" Install="/passive /norestart">
        <Redistributable>
            <Name>Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package MFC Security Update</Name>
            <ShortName>SP1</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=26999</URL>
            <Download>https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe</Download>
        </Redistributable>
    </Platform>
    <Platform Architecture="x86" Release="2010" Install="/passive /norestart">
        <Redistributable>
            <Name>Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package MFC Security Update</Name>
            <ShortName>SP1</ShortName>
            <URL>https://www.microsoft.com/en-us/download/details.aspx?id=26999</URL>
            <Download>https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe</Download>
        </Redistributable>
    </Platform>
    <Platform Architecture="x64" Release="2012" Install="/install /passive /norestart">
        <Redistributable>
